// AUTH
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const LOGOUT = 'LOGOUT'

// PASSWORD RESET
export const PW_REQUEST_SUCCESS = 'PW_REQUEST_SUCCESS'

// APPOINTMENTS
export const GET_SCHEDULE = 'GET_SCHEDULE'
export const GET_MY_APPOINTMENTS = 'GET_MY_APPOINTMENTS'
export const MAKE_APPOINTMENT = 'MAKE_APPOINTMENT'
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT'

// NOTIFICATIONS
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'

// VISUAL (SNACKBARS AND SPINNERS)
export const LOADING = 'LOADING'
export const STOP_LOADING = 'STOP_LOADING'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// CLEANUP
export const RESET_REDUCERS = 'RESET_REDUCERS'
